spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=user
spring.datasource.password=password
spring.flyway.baselineOnMigrate=true

# Had to add this in to fix an error earlier
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
